version: "3.8"

services:
  postgres:
    container_name: clean-code-nestjs-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: clean-code-nestjs
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
